[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "vinson"
version = "1.0.0"
description = "Codebase to predict DNase I accessibility"
requires-python = ">=3.9"
dependencies = [
    "torch",
    "lightning",
    "torchmetrics",
    "numpy",
    "pandas",
    "scipy",
    "scikit-learn",
    "anndata==0.10.9",
    "zarr",
    "dask",
    "h5py",
    "matplotlib",
    "seaborn",
    "mergedeep",
    "numba",
    "pyBigWig",
    "tqdm",
    "PyYAML",
    "genome-tools>=2.0",
    "funkybob",
    "tangermeme",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "build",
]

[tool.setuptools.packages.find]
where = ["src"]
