from IPython.display import display
from tqdm import tqdm_notebook, tqdm

import numpy as np
from numpy.typing import ArrayLike
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader

from genome_tools.genomic_interval import GenomicInterval, VariantInterval, df_to_variant_intervals
from genome_tools.data.extractors import FastaExtractor , TabixExtractor
from vinson.utils.helpers import replace_at
from vinson.utils.sequence_utils import one_hot_encode, get_iupac_char_from_alleles
from vinson.utils.data_formatting.readers import parse_genotype_file
import logging
logger = logging.getLogger(__name__)

# change & place it to file you want or delete =(
# docstring is generated by AI  
# copied your functions for datasets here
class InferenceDataset(Dataset):
    """
    A PyTorch Dataset that generates all combinations of genomic regions, 
    cell-type embeddings, and shifts for model inference.

    Parameters
    ----------
    bed_df : pandas.DataFrame
        DataFrame containing genomic coordinates. 
        Must include columns: ['chrom', 'start', 'end'].
    embed_df : pandas.DataFrame
        DataFrame of cell-type or state embeddings. The index should represent 
        the sample/embedding ID, and the columns should contain the numeric embedding values.
    embed_meta_df : pandas.DataFrame
        DataFrame of meta for each embedding. The index should represent 
        the sample/embedding ID, and the columns should contain at least ['indiv_id'].        
    fasta_file : str
        Path to the reference genome FASTA file.
    genotype_file: str = None
        Path to the file with genotypes of selected samples
    shifts : ArrayLike, optional
        List of spatial shifts (in base pairs) to offset the sequence window. 
        Default is [0].
    seqlen : int, optional
        The fixed total length of the output DNA sequence. Default is 1344.
    """

    REQUIRED_COLUMNS = ['chrom', 'start', 'end']
    
    def __init__(self, 
                 bed_df: pd.DataFrame, 
                 embed_df: pd.DataFrame,
                 fasta_file: str,
                 embed_meta_df: pd.DataFrame = None,
                 genotype_file: str = None,
                 shifts: list = [0], 
                 seqlen: int = 1344 
                 ):

        assert_flag = all([col in bed_df.columns for col in self.REQUIRED_COLUMNS])
        assert assert_flag, 'Ensure all required columns are present'
        
        self.fasta_file = fasta_file
        self.genotype_file = genotype_file

        self.fasta_extr = None
        self.genotype_extr = None 

        is_genotype = genotype_file is not None and genotype_file != ''
        is_embed_meta = embed_meta_df is not None 
        self.include_genotypes = is_embed_meta and is_genotype
        self.embed_meta_df = embed_meta_df
                
        self.coords_chrom = bed_df['chrom'].values
        self.coords_start = bed_df['start'].values
        self.coords_end = bed_df['end'].values
        self.coords_df = bed_df.copy()
        
        self.embeds_ids = embed_df.index.values
        self.embeds_vals = embed_df.astype(np.float32).values

        if self.include_genotypes:
            assert "indiv_id" in self.embed_meta_df.columns, (
                "Sample to genotype mapping must include 'indiv_id' column.")

            self.embed_meta_df = self.embed_meta_df.loc[self.embeds_ids].copy()
            self.indiv_ids = self.embed_meta_df['indiv_id'].values

        else:
            logger.info(
                "No genotyping files provided -- continuing without sample genotypes.")

        self.shifts = np.asarray(shifts)
        self.seqlen = seqlen
        
        self.shape = (len(embed_df), len(self.shifts), len(bed_df))
    
    @classmethod
    def from_anndata(cls, anndata, sample_ids = None, **kwargs):
        embed_df = anndata.obsm['motif_embeddings']
        embed_meta_df = anndata.obs

        if sample_ids is not None:
            embed_df = embed_df.loc[sample_ids]
            embed_meta_df = embed_meta_df.loc[sample_ids]
        else:
            logger.info("No sample_ids is passed, " \
            "all embeddings from anndata will be yielded.")
            
        return cls.__init__(embed_df=embed_df,
                            embed_meta_df=embed_meta_df,
                            **kwargs)
    def __len__(self):
        return self.shape[0] * self.shape[1] * self.shape[2]
        
    def _init_fileread(self):
        if self.fasta_extr is None:
            self.fasta_extr = FastaExtractor(self.fasta_file)
        if self.include_genotypes and self.genotype_extr is None:
            self.genotype_extr = parse_genotype_file(self.genotype_file)

    def _get_window(self, chrom, summit, shift):
        """
        Calculates the genomic interval centered on the provided position.

        Parameters
        ----------
        chrom : str
            Chromosome name.
        summit : int
            Center position of the region.
        shift : int
            Number of base pairs to shift the window from the center.

        Returns
        -------
        GenomicInterval
            The calculated interval object for sequence extraction.
        """
        interval = GenomicInterval(chrom, summit, summit).widen(self.seqlen // 2)
        if shift != 0:
            interval.shift(shift, inplace=True)
        return interval

    def get_sample_sequence(
                self,
                interval: GenomicInterval,
                indiv_id: str,
                reference_variant: VariantInterval=None,
            ):
            """
            
            Returns:
                tuple: (base_sequence str, variants List[Variant])
            """
            seq = self.fasta_extr[interval]
            seq_iupac = seq_ref = seq_alt = str(seq) # modify all 3 regardless
    
            if isinstance(indiv_id, (np.ndarray, list)):
                indiv_id = np.asarray(indiv_id).item()
        
            if pd.isna(indiv_id) or indiv_id in ("None", ""):
                return 0, seq_iupac, seq_ref, seq_alt
        
            assert isinstance(indiv_id, str), f"indiv_id must be str, got {type(indiv_id)}: {indiv_id}"
            assert (
                "INDIV" in indiv_id
            ), f"INDIV_ID format incorrect ({indiv_id}, {type(indiv_id)})."
        
            # Extract variants
            
            try:
                variants = self.genotype_extr[interval]
            except ValueError:
                return 0, seq_iupac, seq_ref, seq_alt
            
            # hotfix
            if variants["indiv_id"].str.endswith(".bed.gz").any():
                key = f"{indiv_id}.bed.gz"
            else:
                key = indiv_id
            
            variants = variants[variants["indiv_id"] == key]
    
            extra_columns = ('gt', )
            #get phased info if exists make sure right format
            if "phase_set" not in variants.columns:
                variants["phase_set"] = None
                
            # If reference_variant is provided, attach gt and phase_set to it
            if reference_variant is not None:
                #if variant spcified not just genotype from dhs model
                try:
                    #find reference variant in variant
                    row = variants.set_index(["chrom", "start", "ref", "alt"]).loc[
                        (reference_variant.chrom, reference_variant.start, reference_variant.ref, reference_variant.alt)
                    ]
        
                except KeyError:
                    #if cannot find variant
                    raise ValueError(
                        f"Reference variant not found in genotyping file: "
                        f"{interval}/{indiv_id}/{reference_variant.start}/{reference_variant.alt}"
                    )
                #get genotype and phase set
                reference_variant.gt = row["gt"]
                phase_val = row.get("phase_set", None)
                reference_variant.phase_set = None if pd.isna(phase_val) or phase_val == "." else phase_val
                extra_columns = ("gt", "phase_set")  # Include phase_set for VariantInterval conversion
        
            # Convert variants to VariantInterval objects
            variants = df_to_variant_intervals(variants, extra_columns=extra_columns)
    
            for v in variants:
    
                rel = v.start - interval.start
    
                if rel >= len(interval) or rel <= 0:
                    #fixes error of trying to replace at end of sequence causing adding extra to end increasing seq len by one
                    continue
        
                # IUPAC sequence
                iupac_base = get_iupac_char_from_alleles(v.ref, v.alt)
                seq_iupac = replace_at(seq_iupac, rel, iupac_base)
        
                # Phased heterozygous handling
                phased_match = (
                    reference_variant is not None
                    and v.gt in ("0|1", "1|0")
                    and reference_variant.phase_set == getattr(v, "phase_set", None)
                )
                if phased_match:
                    if v.gt == "1|0":
                        seq_ref = replace_at(seq_ref, rel, v.alt)
                        seq_alt = replace_at(seq_alt, rel, v.ref)
                    else:
                        seq_ref = replace_at(seq_ref, rel, v.ref)
                        seq_alt = replace_at(seq_alt, rel, v.alt)
                    continue
        
                # Unphased / Homozygous / Heterozygous
                is_het = v.gt[0] != v.gt[2]
                base_ref = v.ref
                base_alt = v.alt if is_het else (v.alt if v.gt[0] == "1" else v.ref)
                seq_ref = replace_at(seq_ref, rel, base_ref)
                seq_alt = replace_at(seq_alt, rel, base_alt)
        
            # Final check for reference variant
            if reference_variant is not None:
                rel_pos = reference_variant.start - interval.start
                if reference_variant.gt == "1|0":
                    seq_ref, seq_alt = seq_alt, seq_ref
                    
                if (seq_ref[rel_pos] != reference_variant.ref) or (seq_alt[rel_pos] != reference_variant.alt):
                    raise ValueError(
                        f"Expected ref & alt alleles not found in correct position "
                        f"(reference_variant={reference_variant}, indiv_id={indiv_id})"
                    )
    
            return len(variants), seq_iupac, seq_ref, seq_alt
    
    def _crop(self, dna_seq: str):
        """
        Trims the DNA sequence back to the target `seqlen`.

        Parameters
        ----------
        dna_seq : str
            The target DNA sequence.

        Returns
        -------
        str
            The center-cropped DNA sequence matching `seqlen`.
        """
        if len(dna_seq) > self.seqlen:
            mid = len(dna_seq) // 2
            dna_seq = dna_seq[mid - self.seqlen//2 : mid + self.seqlen//2]
        return dna_seq
    
    def prepare_meta(self):
        """
        Generates a flat metadata DataFrame matching the exact iteration order of __getitem__.

        Returns
        -------
        pandas.DataFrame
            DataFrame containing genomic region details, shift values, and embedding IDs 
            for every sample in the dataset.
        """
        # dtypes = {
        #     'chrom': 'category',
        #     'embed_id': 'category',      
        #     'shift': 'category',     
        # }
        idxs = np.arange(len(self))
        embeds_idxs, shift_idxs, coord_idxs = np.unravel_index(idxs, self.shape)
        
        df = self.coords_df.iloc[coord_idxs].copy()
        df['shift'] = self.shifts[shift_idxs]
        df['embed_id'] = self.embeds_ids[embeds_idxs]
        
        # df = df.astype(dtypes)
        return df.reset_index(drop=True)

    def __getitem__(self, idx):
        """
        Retrieves a single batch item containing the one-hot encoded sequence and its embedding.

        Parameters
        ----------
        idx : int
            The flattened integer index of the dataset.

        Returns
        -------
        dict
            A dictionary containing the model inputs:
            - 'seq': One-hot encoded DNA sequence of the specified genomic region.
            - 'seq_revcomp': Reverse complement of the one-hot encoded sequence.
            - 'embed': The cell-type or state embedding array.
        """
        self._init_fileread()
        
        x, y, z = np.unravel_index(idx, shape=self.shape)
        
        embed = self.embeds_vals[x]
        shift = int(self.shifts[y])
        
        chrom = self.coords_chrom[z]
        start = self.coords_start[z]
        end = self.coords_end[z]
        
        summit = (start + end) // 2
        interval = self._get_window(chrom, summit, shift)

        
        if self.include_genotypes:
            indiv_id = self.indiv_ids[x]
            _, dna_seq, _, _ = self.get_sample_sequence(interval, indiv_id)
        else:
            dna_seq = self.fasta_extr[interval].upper()

        ohe_seq = one_hot_encode(dna_seq)

        batch = dict(
            seq = ohe_seq.copy(),
            seq_revcomp = np.flip(ohe_seq, [0, 1]).copy(),
            embed = embed.copy()
        )
        return batch


class InferenceVariantDataset(InferenceDataset):
    """
    A PyTorch Dataset that generates all combinations of genetic variants, 
    cell-type embeddings, and shifts for model inference.

    Parameters
    ----------
    variants_df : pandas.DataFrame
        DataFrame containing variant coordinates and alleles. 
        Must include columns: ['chrom', 'pos', 'ref', 'alt'].
    embed_df : pandas.DataFrame
        DataFrame of cell-type or state embeddings. The index should represent 
        the sample/embedding ID, and the columns should contain the numeric embedding values.
    fasta_file : str
        Path to the reference genome FASTA file.
    shifts : ArrayLike, optional
        List of spatial shifts (in base pairs) to offset the sequence window. 
        Default is [0].
    seqlen : int, optional
        The fixed total length of the output DNA sequence. Default is 1344.
    """

    REQUIRED_COLUMNS = ['chrom', 'pos', 'ref', 'alt']
    
    def __init__(self, 
                 variants_df: pd.DataFrame, 
                 embed_df: pd.DataFrame,
                 fasta_file: str,
                 embed_meta_df: pd.DataFrame = None,
                 genotype_file: str = None,
                 shifts: list = [0], 
                 seqlen: int = 1344,
                 
                 ):
        assert_flag = all([col in variants_df.columns for col in self.REQUIRED_COLUMNS])
        assert assert_flag, 'Ensure all required columns are present'
        
        self.fasta_file = fasta_file
        self.fasta_extr = None
        self.genotype_extr = None 

        is_genotype = genotype_file is not None and genotype_file != ''
        is_embed_meta = embed_meta_df is not None and embed_meta_df != '' 
        self.include_genotypes = is_embed_meta and is_genotype
            
        if self.include_genotypes:
            assert "indiv_id" in self.embed_meta_df.columns, (
                "Sample to genotype mapping must include 'indiv_id' column.")

            self.embed_meta_df = self.embed_meta_df.loc[self.embeds_ids].copy()
            self.indiv_ids = self.embed_meta_df['indiv_id'].values
            
        else:
            logger.info(
                "No genotyping files provided -- continuing without sample genotypes.")
        
        self.coords_chrom = variants_df['chrom'].values
        self.coords_pos = variants_df['pos'].values
        self.coords_ref = variants_df['ref'].values
        self.coords_alt = variants_df['alt'].values
        self.coords_df = variants_df.copy()
        
        self.embeds_ids = embed_df.index.values
        self.embeds_vals = embed_df.astype(np.float32).values
        
        self.shifts = np.asarray(shifts)
        self.seqlen = seqlen
        
        self.shape = (len(embed_df), len(self.shifts), len(variants_df))
    
    def _prepare_alleles(self, dna_seq, rel_pos, ref, alt):
        """
        Extracts the reference sequence and constructs the alternative sequence.

        Parameters
        ----------
        interval : GenomicInterval
            The target genomic window.
        pos : int
            The absolute genomic coordinate of the variant.
        ref : str
            The reference allele.
        alt : str
            The alternative allele.

        Returns
        -------
        tuple of str
            The reference and alternative DNA sequences (uppercase).
        """

        dna_seq_ref = dna_seq_alt = dna_seq #self.fasta_extr[interval]
        dna_seq_ref = replace_at(dna_seq_ref, rel_pos, ref)

        if alt in ('', '.', '-', '_'): # in case there is deletion
            alt = ''
            interval = interval.widen(left=0, right=1)
            dna_seq_alt = self.fasta_extr[interval]

        dna_seq_alt = self._crop(replace_at(dna_seq_alt, rel_pos, alt))
        return dna_seq_ref.upper(), dna_seq_alt.upper()
    
    def prepare_meta(self):
        """
        Generates a flat metadata DataFrame matching the exact iteration order of __getitem__.

        Returns
        -------
        pandas.DataFrame
            DataFrame containing variant details, shift values, embedding IDs, 
            and a unique string identifier (`var_id`) for every sample in the dataset.
        """
        dtypes = {
            'ref' : 'category',
            'alt' : 'category',
            'chrom': 'category',
            'embed_id': 'category',      
            'shift': 'category',     
            'var_id': 'str'  
        }
        idxs = np.arange(len(self))
        embeds_idxs, shift_idxs, coord_idxs = np.unravel_index(idxs, self.shape)
        
        df = self.coords_df.iloc[coord_idxs].copy()
        df['shift'] = self.shifts[shift_idxs]
        df['embed_id'] = self.embeds_ids[embeds_idxs]
        df['var_id'] = df.chrom.astype(str) + '_' + df.pos.astype(str) + '_' + df.ref + '_' + df.alt
        
        # df = df.astype(dtypes)
        return df.reset_index(drop=True)

    def __getitem__(self, idx):
        """
        Retrieves a single batch item containing one-hot encoded alleles and metadata.

        Parameters
        ----------
        idx : int
            The flattened integer index of the dataset.

        Returns
        -------
        dict
            A dictionary containing:
            - 'ref': One-hot encoded reference sequence.
            - 'ref_revcomp': Reverse complement of the reference sequence.
            - 'alt': One-hot encoded alternative sequence.
            - 'alt_revcomp': Reverse complement of the alternative sequence.
            - 'embed': The cell-type embedding array.
        """
        self._init_fileread()
        
        x, y, z = np.unravel_index(idx, shape=self.shape)
        
        embed = self.embeds_vals[x]
        shift = int(self.shifts[y])
        
        chrom = self.coords_chrom[z]
        pos = self.coords_pos[z]
        ref = self.coords_ref[z]
        alt = self.coords_alt[z]

        interval = self._get_window(chrom, pos, shift)

        if self.include_genotypes:
            indiv_id = self.indiv_ids[x]
            _, dna_seq, _, _ = self.get_sample_sequence(interval, indiv_id)
        else:
            dna_seq = self.fasta_extr[interval].upper()

        start = pos - 1
        rel_pos = start - interval.start

        dna_seq_ref, dna_seq_alt = self._prepare_alleles(dna_seq, rel_pos, ref, alt)
        
        ohe_seq_ref = one_hot_encode(dna_seq_ref)
        ohe_seq_alt = one_hot_encode(dna_seq_alt)

        batch = dict(
            ref = ohe_seq_ref.copy(),
            ref_revcomp = np.flip(ohe_seq_ref, [0, 1]).copy(),
            alt = ohe_seq_alt.copy(),
            alt_revcomp = np.flip(ohe_seq_alt, [0, 1]).copy(),
            embed = embed.copy()
        )
        return batch



def score_variants_with_dhs_model(variants, embeds_df, fasta_file,
                           shifts, 
                           model,
                           dataloader_kwargs, device):

    dataset = InferenceVariantDataset(variants, embeds_df, fasta_file, 
                           shifts=shifts) 
    dataloader = DataLoader(dataset, 
                            **dataloader_kwargs)
    lst_ref, lst_alt = [], []

    with torch.no_grad():    
        for batch in tqdm_notebook(dataloader):
            ref, ref_revcomp = batch['ref'].to(device), batch['ref_revcomp'].to(device)
            alt, alt_revcomp = batch['alt'].to(device), batch['alt_revcomp'].to(device)
            embeds = batch['embed'].to(device)

            pred_ref, pred_ref_revcomp = model(ref, embeds), model(ref_revcomp, embeds)
            pred_alt, pred_alt_revcomp = model(alt, embeds), model(alt_revcomp, embeds)

            ## geom mean
            pred_ref = (torch.log(pred_ref) + torch.log(pred_ref_revcomp))/2
            pred_alt = (torch.log(pred_alt) + torch.log(pred_alt_revcomp))/2
            pred_ref, pred_alt = torch.exp(pred_ref), torch.exp(pred_alt)
            
            lst_ref.append(pred_ref.cpu().numpy()), lst_alt.append(pred_alt.cpu().numpy())

    ref_scores, alt_scores = np.concatenate(lst_ref), np.concatenate(lst_alt)
    out_df = dataset.prepare_meta()
    out_df['vinson.ref_score'] = ref_scores
    out_df['vinson.alt_score'] = alt_scores
    return out_df



def assemble_batch(sample_id, interval, embeddings, fasta):
    """
    Assemble batch from sample_id, interval and embedding
    
    Parameters
    -------------
    sample_id: str
        Sample id, for example AGXXXXX
    interval: GenomicInterval 
        The target genomic window.
    embeddings: pandas.DataFrame
        DataFrame with embeddings, index must be sample_id
    fasta: str
        Path to fasta file with genome 
    """

    with FastaExtractor(fasta) as ext:
        seq = ext[interval]
    dl = DataLoader(
        [
            {
                'ohe_seq': one_hot_encode(seq.upper(), dtype=np.float32),
                'sample_id': sample_id,
                'summit': interval.center.start,
                'chrom': interval.chrom,
                'embed': embeddings.loc[sample_id].values.astype(np.float32)
            }
        ]
    )

    return next(iter(dl))