model_type: variant
model_kwargs:
  log_output: true
train_augmentation_kwargs:
  reverse_complement: true
  jitter: 5
  noise: 0.01
validation_augmentation_kwargs:
  reverse_complement: false
  jitter: 0
  noise: 0
hparams:
  batch_size: 64
  optimizer_kwargs:
    lr: 1.0e-05
data_params:
  clip_density: 20
  min_bg: 0.1
  negatives_weight: 1
logging_params:
  val_check_interval: 0.2
  logger_type: csv