model_type: variant
train_augmentation_kwargs:
  reverse_complement: true
  jitter: 5
  noise: 0.01
validation_augmentation_kwargs:
  reverse_complement: false
  jitter: 0
  noise: 0
hparams:
  batch_size: 64
  optimizer_kwargs:
    lr: 1.0e-05
logging_params:
  val_check_interval: 0.2
  logger_type: csv