model_type:
  legnet_variant_embed


model_arch:
  n_independent_embeds: 4

  cell_embed:
    n_inputs: 637
    hidden_dims: [318]
    batch_norm: true
    dropout: 0
    batch_norm_momentum: 0.1
    activations: 'silu'
    order: 'fc-drop-bn-act' #'fc-drop-bn-act'
  
  trunk:
    in_ch: 4
    stem_ch: 200             
    ef_block_sizes: [216, 232, 248, 264]
    ef_ks: 9       
    stem_ks: [6, 9, 12, 15]             
    pool_sizes: [4, 4, 2, 2]            
    resize_factor: 4

  head:
    n_inputs: 1056 # x2 ef_block_size[-1]
    hidden_dims: [1056, 1056]
    batch_norm: true
    dropout: 0.05
    batch_norm_momentum: 0.1
    activations: 'silu'
    order: 'fc-drop-bn-act' #'fc-drop-bn-act'
     
hparams:
  batch_size: 128
  epochs: 15
  lr_scheduler: None
  optimizer_kwargs:
    lr: 1.0e-06
    
dataloader_kwargs:
  batch_size: 128
trainer_kwargs:
  early_stopping_patience: 25
  freeze_trunk_epochs: 1

train_augmentation_kwargs:
  reverse_complement: true
  flip_alleles: true
  jitter: 20
validation_augmentation_kwargs:
  reverse_complement: false
  flip_alleles: false
  jitter: 0
logging_params:
  val_check_interval: 0.2
  logger_type: csv