model_type: basset_embed

model_kwargs:
  log_output: false
  n_independent_embeds: 1

model_arch:
  n_independent_embeds: 4

  cell_embed:
    n_inputs: 637
    hidden_dims: [637]
    batch_norm: true
    dropout: 0
    batch_norm_momentum: 0.1
    activations: 'silu'
    order: 'fc-drop-bn-act' # fc-drop-act-bn
  
  head:
    n_inputs: 256
    hidden_dims: [128, 64]
    batch_norm: true
    batch_norm_momentum: 0.1
    activation: silu
    order: 'fc-drop-bn-act' # fc-drop-act-bn

  trunk:
    activation: silu

hparams:
  epochs: 3

  optimizer_kwargs:
    weight_decay: 1.0e-2

  lr_scheduler: OneCycleLR
  lr_scheduler_kwargs:
    max_lr: 1.0e-03
    div_factor: 25
    final_div_factor: 10000
    total_steps: null

dataloader_kwargs:
  pre_jitter: false
  batch_size: 1024

train_augmentation_kwargs:
  reverse_complement: true
  jitter: 20
  noise: 0.1
validation_augmentation_kwargs:
  reverse_complement: false
  jitter: 0
  noise: 0
data_params:
  clip_density: 20
  min_bg: 0.1
  negatives_weight: 1

logging_params:
  val_check_interval: 0.2
  logger_type: csv