model_type:
  legnet_embed
model_kwargs:        
  log_output: false
  n_tasks: 1
  regression: true

model_arch:
  cell_embed:
    n_inputs: 637
    hidden_dims: [256, 128]
    batch_norm: true
    dropout: 0.2
    batch_norm_momentum: 0.1
    activations: 'silu'
  
  trunk:
    in_ch : 4
    stem_ch: 96             
    ef_block_sizes: [112, 128, 142, 158]
    ef_ks: 9       
    stem_ks: [6,9,12,15]             
    pool_sizes: [4, 4, 2, 2]            
    resize_factor: 4

  head:
    n_inputs: 316 # x2 ef_block_size[-1]
    hidden_dims: [316]
    batch_norm: true
    dropout: 0.2
    batch_norm_momentum: 0.1
    activations: 'silu'
     
hparams:
  batch_size: 1024
  epochs: 3
  optimizer_kwargs:
    wd: 1.0e-2
  lr_scheduler: OneCycleLR
  lr_scheduler_kwargs:
    max_lr: 1.0e-3
    div_factor: 25
    final_div_factor: 10000
    total_steps: null

data_params:
  clip_density: 20
  min_bg: 0.1
  negatives_weight: 1
train_augmentation_kwargs:
  reverse_complement: true
  noise: 0.1
  jitter: 40
validation_augmentation_kwargs:
  reverse_complement: false
  noise: 0
  jitter: 0
logging_params:
  val_check_interval: 0.2
  logger_type: csv