model_type: regression
model_kwargs:
  log_output: false
hparams:
  batch_size: 32
  lr: 1.0e-05
  lr_scheduler: OneCycleLR
  lr_scheduler_kwargs:
    max_lr: 1.0e-03
    div_factor: 25
    final_div_factor: 10000
data_params:
  clip_density: 20
  min_bg: 0.1
  negatives_weight: 1
logging_params:
  val_check_interval: 0.5
  logger_type: csv